runtime: java
vm: true

# [START env_variables]
env_variables:
  TWILIO_ACCOUNT_SID: YOUR-TWILIO-ACCOUNT-SID
  TWILIO_AUTH_TOKEN: YOUR-TWILIO-AUTH-TOKEN
  TWILIO_NUMBER: YOUR-TWILIO-NUMBER
# [END env_variables]

