runtime: java
vm: true
runtime_config:
  jdk: openjdk8
  server: jetty9

# [START env_variables]
env_variables:
  SQL_DATABASE_URL: jdbc:mysql://HOST-IP:3306/YOUR-DB-NAME?user=USERNAME&password=PASSWORD
# [END env_variables]
